version: '3.4'

services: 
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    volumes: 
      - ./data/mssql:/var/opt/mssql
    ports:
      - "5433:1433"


  yow.api:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Yow.Service.ChatDb;User Id=sa;Password=Pass@word
    ports: 
      - "5100:80"

  